Django_Shop/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url,include

urlpatterns = [
    url('^admin/', admin.site.urls),
    url('^cart/',include('cart.urls')),
    url('^paypal/',include('paypal.standard.ipn.urls')),
    url('^templates/',include('payment.urls')),
    url('^',include('shop.urls')),
    url('^orders/',include('orders.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import url
from . import views

app_name='cart'
urlpatterns=[
    url(r'^$',views.cart_detail,name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$',views.cart_add,name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$',views.cart_remove,name='cart_remove'),
]

orders/urls.py
from django.conf.urls import url
from . import views

app_name='orders'
urlpatterns=[
    url(r'^create/$',views.order_create,name='order_create'),
]

shop/urls.py
from django.conf.urls import url
from . import views

app_name='shop'
urlpatterns=[
    url(r'^$',views.product_list,name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$',views.product_list,name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',views.product_detail,name='product_detail'),
]

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES=[(i,str(i)) for i in range(1,201)]

class CartAddProductForm(forms.Form):
    quantity=forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,coerce=int)
    update=forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .forms import CartAddProductForm
from shop.models import Product
from .cart import Cart
from django.views.decorators.http import require_POST

def cart_detail(request):
    cart=Cart(request)
    for item in cart:
        item['update_quantity_form']=CartAddProductForm(initial={'quantity':item['quantity'],
                                                        'update':True,}
                                                        )
    return render(request,'cart/detail.html',{'cart':cart})
    pass

@require_POST
def cart_add(request,product_id):
    cart=Cart(request)
    product=get_object_or_404(Product,id=product_id)
    form=CartAddProductForm(request.POST)
    if form.is_valid():
        cd=form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request,product_id):
    cart=Cart(request)
    product=get_object_or_404(Product,id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

cart/templates/cart/detail.html
{% extends 'shop/base.html' %}
{% load staticfiles %}

{% block title %}
    您的商品购物车
{% endblock %}
{% block content %}
    <h1>您的商品购物车</h1>
    <table class="cart">
        <thead>
            <tr>
                <th>Image</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Remove</th>
                <th>Unit price</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
                {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>
                        <form action="{% url 'cart:cart_add' product.id %}" method="post">
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.update }}
                            {% csrf_token %}
                            <input type="submit" value="更新">
                        </form>
                    </td>
                    <td>
                        <a href="{% url 'cart:cart_remove' product.id %}">移除</a>
                    </td>
                    <td>{{ item.price }}</td>
                    <td>{{ item.total_price }}</td>
                </tr>
                {% endwith %}
            {% endfor %}
            <tr class="total">
                <td>总计</td>
                <td colspan="4"></td>
                <td class="num">{{ cart.get_total_price }}</td>
            </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url 'shop:product_list' %}" class="button">继续购物</a>
        <a href="{% url 'orders:order_create' %}" class="button">结算</a>
    </p>
{% endblock %}